export {
  typeRefkey,
  serializerRefkey,
  deserializerRefkey,
  polymorphicTypeRefkey,
  knownValuesRefkey,
  operationOptionsRefkey,
  clientContextRefkey,
  createClientRefkey,
  clientOptionsRefkey,
  classicalClientRefkey,
  xmlSerializerRefkey,
  xmlDeserializerRefkey,
  serializationHelperRefkey,
  pagingHelperRefkey,
  pollingHelperRefkey,
  sendOperationRefkey,
  deserializeOperationRefkey,
  publicOperationRefkey,
} from "./refkeys.js";

export {
  httpRuntimeLib,
  azureCoreClientLib,
  azureCorePipelineLib,
  azureAbortControllerLib,
  azureCoreUtilLib,
  azureCoreAuthLib,
  azureCoreLroLib,
  azureIdentityLib,
} from "./external-packages.js";
